### PR TITLE
Update to version 0.8.0

### PR DESCRIPTION
**Pull request by jnothman**
I'm not certain that this is all that is needed, but let's give it a try.

Ping @rgommers

### CODE REVIEW

**Comment by rgommers** [comment]
line one of this file contains the version number, that should be changed to 0.8.0. That plus the sha hash should be enough.

**Comment by jnothman** [comment]
I missed that. I'll try fix it up later. Not working by mobile

**Comment by jakirkham** [comment]
In the interim, it appears the bot pushed an update. ( https://github.com/conda-forge/numpydoc-feedstock/pull/4 ) Would you like to fix this up or should we go ahead with that PR?

**Comment by jschueller** [comment]
see #4

**Comment by jnothman** [comment]
it would be nice if the readme mentioned the bot to avoid duplicated effort

**Comment by jakirkham** [comment]
The bot is very new and still under active development. For instance, it currently does not know how to identify that another version update PR exists. ( https://github.com/regro/cf-scripts/issues/16 ) We are aware of these limitations and are tracking them upstream. Sorry for any trouble it caused.

**Comment by jnothman** [comment]
No trouble. Thanks

**Pull request closed without merging**
